### ISSUE TITLE
Categories are not being set properly.  

### ISSUE THREAD

**Issue by cazador481** [cazador481/MooX-Log-Any#4]
They are being set to MooX::log::Any 
To fix init with Log::Any->get_logger(category=>ref shift);

**Comment by kjetilk** [comment]
This would be really nice to have. 

Alternatively, create a new attribute that does this, in case existing users don't care about categories.

Anyway, it would be wonderful if you found some time to fix this. :-)

Cheers,

Kjetil

**Comment by cazador481** [comment]
I fixed this in version 0.003 .  Guess I never closed the issue.
Also if you explicitly want to set a category for a message you can do $self->logger('category')->debug('message').
If you find that this wasn't fix please reopen the bug.

**Comment by kjetilk** [comment]
Ah, OK, sorry for not checking, I just saw the issue and since I had seen this in other people's code found that it is something that ought to be in there... :-)

**Comment by kjetilk** [comment]
Actually, the ref shift default category doesn't seem to be in there...

**Comment by cazador481** [comment]
Looks like you are right.  I use log4perl, and have it taken care of in my log4perl config.  Will release a fix soon.

**Comment by cazador481** [comment]
Fixed in https://github.com/cazador481/MooX-Log-Any/commit/b96b8a42d15b2d357719ff48175ac74eaaf79bf1
