### ISSUE TITLE
The module PERL isn't available on CPAN

### ISSUE THREAD

**Issue by rehsack** [cazador481/MooX-Log-Any#8]
There is no "PERL" - it's "perl" ;)

  Running install for module 'MooX::Log::Any'
  Checksum for /home/jrehsack/.cpan/sources/authors/id/C/CA/CAZADOR/MooX-Log-Any-0.003001.tar.gz ok
  Configuring C/CA/CAZADOR/MooX-Log-Any-0.003001.tar.gz with Makefile.PL
  Checking if your kit is complete...
  Looks good
  Warning: prerequisite PERL 5.006 not found.
  Generating a Unix-style Makefile
  Writing Makefile for MooX::Log::Any
  Writing MYMETA.yml and MYMETA.json
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
    ~/perl5/perlbrew/perls/perl-5.20.1/bin/perl Makefile.PL -- OK
  Running make for C/CA/CAZADOR/MooX-Log-Any-0.003001.tar.gz
  ---- Unsatisfied dependencies detected during ----
  ----   CAZADOR/MooX-Log-Any-0.003001.tar.gz   ----
      PERL [requires]
  Running install for module 'PERL'
  
    The module PERL isn't available on CPAN.
  
    Either the module has not yet been uploaded to CPAN, or it is
    temporary unavailable. Please contact the author to find out
    more about the status. Try 'i PERL'.
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
    Has already been unwrapped into directory ~/.cpan/build/MooX-Log-Any-0.003001-Kn6cpy
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
    Has already been prepared
  Running make for C/CA/CAZADOR/MooX-Log-Any-0.003001.tar.gz
  cp lib/MooX/Log/Any.pm blib/lib/MooX/Log/Any.pm
  Manifying 1 pod document
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
    /usr/bin/make -- OK
  Running make test
  PERL_DL_NONLAZY=1 "~/perl5/perlbrew/perls/perl-5.20.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
  t/l0.t .................... ok   
  t/release-test-version.t .. skipped: these tests are for release candidate testing
  All tests successful.
  Files=2, Tests=2,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.09 cusr  0.00 csys =  0.11 CPU)
  Result: PASS
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
  Tests succeeded but one dependency not OK (PERL)
    CAZADOR/MooX-Log-Any-0.003001.tar.gz
    [dependencies] -- NA

**Comment by cazador481** [comment]
Fixed in 0.004
